# Generated by Django 3.2.7 on 2021-12-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('در حال بررسی', 'در حال بررسی'), ('سفارشات در مسیر تحویل', 'سفارشات در مسیر تحویل'), ('تحویل داده شده', 'تحویل داده شده')], max_length=200, null=True),
        ),
    ]
